//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.entities
{
   using System;
   using System.Runtime.Serialization;
   
   public partial class Account : app.entities.ExtendedEntity
   {
      [DataMember(Name="accountid")]
      public System.Guid AccountId
      {
         get
         {
            return base.GetAttributeValue<System.Guid>("accountid");
         }
      }
      [DataMember(Name="accountnumber")]
      public string AccountNumber
      {
         get
         {
            return base.GetAttributeValue<string>("accountnumber");
         }
         set
         {
            base.SetAttributeValue<string>("accountnumber", value);
         }
      }
      [DataMember(Name="address1_city")]
      public string Address1_City
      {
         get
         {
            return base.GetAttributeValue<string>("address1_city");
         }
         set
         {
            base.SetAttributeValue<string>("address1_city", value);
         }
      }
      [DataMember(Name="address1_composite")]
      public string Address1_Composite
      {
         get
         {
            return base.GetAttributeValue<string>("address1_composite");
         }
      }
      [DataMember(Name="address1_country")]
      public string Address1_Country
      {
         get
         {
            return base.GetAttributeValue<string>("address1_country");
         }
         set
         {
            base.SetAttributeValue<string>("address1_country", value);
         }
      }
      [DataMember(Name="address1_county")]
      public string Address1_County
      {
         get
         {
            return base.GetAttributeValue<string>("address1_county");
         }
         set
         {
            base.SetAttributeValue<string>("address1_county", value);
         }
      }
      [DataMember(Name="address1_fax")]
      public string Address1_Fax
      {
         get
         {
            return base.GetAttributeValue<string>("address1_fax");
         }
         set
         {
            base.SetAttributeValue<string>("address1_fax", value);
         }
      }
      [DataMember(Name="address1_latitude")]
      public System.Nullable<double> Address1_Latitude
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<double>>("address1_latitude");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<double>>("address1_latitude", value);
         }
      }
      [DataMember(Name="address1_line1")]
      public string Address1_Line1
      {
         get
         {
            return base.GetAttributeValue<string>("address1_line1");
         }
         set
         {
            base.SetAttributeValue<string>("address1_line1", value);
         }
      }
      [DataMember(Name="address1_line2")]
      public string Address1_Line2
      {
         get
         {
            return base.GetAttributeValue<string>("address1_line2");
         }
         set
         {
            base.SetAttributeValue<string>("address1_line2", value);
         }
      }
      [DataMember(Name="address1_line3")]
      public string Address1_Line3
      {
         get
         {
            return base.GetAttributeValue<string>("address1_line3");
         }
         set
         {
            base.SetAttributeValue<string>("address1_line3", value);
         }
      }
      [DataMember(Name="address1_longitude")]
      public System.Nullable<double> Address1_Longitude
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<double>>("address1_longitude");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<double>>("address1_longitude", value);
         }
      }
      [DataMember(Name="address1_name")]
      public string Address1_Name
      {
         get
         {
            return base.GetAttributeValue<string>("address1_name");
         }
         set
         {
            base.SetAttributeValue<string>("address1_name", value);
         }
      }
      [DataMember(Name="address1_postalcode")]
      public string Address1_PostalCode
      {
         get
         {
            return base.GetAttributeValue<string>("address1_postalcode");
         }
         set
         {
            base.SetAttributeValue<string>("address1_postalcode", value);
         }
      }
      [DataMember(Name="address1_postofficebox")]
      public string Address1_PostOfficeBox
      {
         get
         {
            return base.GetAttributeValue<string>("address1_postofficebox");
         }
         set
         {
            base.SetAttributeValue<string>("address1_postofficebox", value);
         }
      }
      [DataMember(Name="address1_primarycontactname")]
      public string Address1_PrimaryContactName
      {
         get
         {
            return base.GetAttributeValue<string>("address1_primarycontactname");
         }
         set
         {
            base.SetAttributeValue<string>("address1_primarycontactname", value);
         }
      }
      [DataMember(Name="address1_stateorprovince")]
      public string Address1_StateOrProvince
      {
         get
         {
            return base.GetAttributeValue<string>("address1_stateorprovince");
         }
         set
         {
            base.SetAttributeValue<string>("address1_stateorprovince", value);
         }
      }
      [DataMember(Name="address1_telephone1")]
      public string Address1_Telephone1
      {
         get
         {
            return base.GetAttributeValue<string>("address1_telephone1");
         }
         set
         {
            base.SetAttributeValue<string>("address1_telephone1", value);
         }
      }
      [DataMember(Name="address1_telephone2")]
      public string Address1_Telephone2
      {
         get
         {
            return base.GetAttributeValue<string>("address1_telephone2");
         }
         set
         {
            base.SetAttributeValue<string>("address1_telephone2", value);
         }
      }
      [DataMember(Name="address1_telephone3")]
      public string Address1_Telephone3
      {
         get
         {
            return base.GetAttributeValue<string>("address1_telephone3");
         }
         set
         {
            base.SetAttributeValue<string>("address1_telephone3", value);
         }
      }
      [DataMember(Name="address1_upszone")]
      public string Address1_UPSZone
      {
         get
         {
            return base.GetAttributeValue<string>("address1_upszone");
         }
         set
         {
            base.SetAttributeValue<string>("address1_upszone", value);
         }
      }
      [DataMember(Name="address1_utcoffset")]
      public System.Nullable<int> Address1_UTCOffset
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("address1_utcoffset");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<int>>("address1_utcoffset", value);
         }
      }
      [DataMember(Name="address2_city")]
      public string Address2_City
      {
         get
         {
            return base.GetAttributeValue<string>("address2_city");
         }
         set
         {
            base.SetAttributeValue<string>("address2_city", value);
         }
      }
      [DataMember(Name="address2_composite")]
      public string Address2_Composite
      {
         get
         {
            return base.GetAttributeValue<string>("address2_composite");
         }
      }
      [DataMember(Name="address2_country")]
      public string Address2_Country
      {
         get
         {
            return base.GetAttributeValue<string>("address2_country");
         }
         set
         {
            base.SetAttributeValue<string>("address2_country", value);
         }
      }
      [DataMember(Name="address2_county")]
      public string Address2_County
      {
         get
         {
            return base.GetAttributeValue<string>("address2_county");
         }
         set
         {
            base.SetAttributeValue<string>("address2_county", value);
         }
      }
      [DataMember(Name="address2_fax")]
      public string Address2_Fax
      {
         get
         {
            return base.GetAttributeValue<string>("address2_fax");
         }
         set
         {
            base.SetAttributeValue<string>("address2_fax", value);
         }
      }
      [DataMember(Name="address2_latitude")]
      public System.Nullable<double> Address2_Latitude
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<double>>("address2_latitude");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<double>>("address2_latitude", value);
         }
      }
      [DataMember(Name="address2_line1")]
      public string Address2_Line1
      {
         get
         {
            return base.GetAttributeValue<string>("address2_line1");
         }
         set
         {
            base.SetAttributeValue<string>("address2_line1", value);
         }
      }
      [DataMember(Name="address2_line2")]
      public string Address2_Line2
      {
         get
         {
            return base.GetAttributeValue<string>("address2_line2");
         }
         set
         {
            base.SetAttributeValue<string>("address2_line2", value);
         }
      }
      [DataMember(Name="address2_line3")]
      public string Address2_Line3
      {
         get
         {
            return base.GetAttributeValue<string>("address2_line3");
         }
         set
         {
            base.SetAttributeValue<string>("address2_line3", value);
         }
      }
      [DataMember(Name="address2_longitude")]
      public System.Nullable<double> Address2_Longitude
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<double>>("address2_longitude");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<double>>("address2_longitude", value);
         }
      }
      [DataMember(Name="address2_name")]
      public string Address2_Name
      {
         get
         {
            return base.GetAttributeValue<string>("address2_name");
         }
         set
         {
            base.SetAttributeValue<string>("address2_name", value);
         }
      }
      [DataMember(Name="address2_postalcode")]
      public string Address2_PostalCode
      {
         get
         {
            return base.GetAttributeValue<string>("address2_postalcode");
         }
         set
         {
            base.SetAttributeValue<string>("address2_postalcode", value);
         }
      }
      [DataMember(Name="address2_postofficebox")]
      public string Address2_PostOfficeBox
      {
         get
         {
            return base.GetAttributeValue<string>("address2_postofficebox");
         }
         set
         {
            base.SetAttributeValue<string>("address2_postofficebox", value);
         }
      }
      [DataMember(Name="address2_primarycontactname")]
      public string Address2_PrimaryContactName
      {
         get
         {
            return base.GetAttributeValue<string>("address2_primarycontactname");
         }
         set
         {
            base.SetAttributeValue<string>("address2_primarycontactname", value);
         }
      }
      [DataMember(Name="address2_stateorprovince")]
      public string Address2_StateOrProvince
      {
         get
         {
            return base.GetAttributeValue<string>("address2_stateorprovince");
         }
         set
         {
            base.SetAttributeValue<string>("address2_stateorprovince", value);
         }
      }
      [DataMember(Name="address2_telephone1")]
      public string Address2_Telephone1
      {
         get
         {
            return base.GetAttributeValue<string>("address2_telephone1");
         }
         set
         {
            base.SetAttributeValue<string>("address2_telephone1", value);
         }
      }
      [DataMember(Name="address2_telephone2")]
      public string Address2_Telephone2
      {
         get
         {
            return base.GetAttributeValue<string>("address2_telephone2");
         }
         set
         {
            base.SetAttributeValue<string>("address2_telephone2", value);
         }
      }
      [DataMember(Name="address2_telephone3")]
      public string Address2_Telephone3
      {
         get
         {
            return base.GetAttributeValue<string>("address2_telephone3");
         }
         set
         {
            base.SetAttributeValue<string>("address2_telephone3", value);
         }
      }
      [DataMember(Name="address2_upszone")]
      public string Address2_UPSZone
      {
         get
         {
            return base.GetAttributeValue<string>("address2_upszone");
         }
         set
         {
            base.SetAttributeValue<string>("address2_upszone", value);
         }
      }
      [DataMember(Name="address2_utcoffset")]
      public System.Nullable<int> Address2_UTCOffset
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("address2_utcoffset");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<int>>("address2_utcoffset", value);
         }
      }
      [DataMember(Name="aging30")]
      public System.Nullable<decimal> Aging30
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("aging30");
         }
      }
      [DataMember(Name="aging30_base")]
      public System.Nullable<decimal> Aging30_Base
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("aging30_base");
         }
      }
      [DataMember(Name="aging60")]
      public System.Nullable<decimal> Aging60
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("aging60");
         }
      }
      [DataMember(Name="aging60_base")]
      public System.Nullable<decimal> Aging60_Base
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("aging60_base");
         }
      }
      [DataMember(Name="aging90")]
      public System.Nullable<decimal> Aging90
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("aging90");
         }
      }
      [DataMember(Name="aging90_base")]
      public System.Nullable<decimal> Aging90_Base
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("aging90_base");
         }
      }
      [DataMember(Name="createdbyexternalpartyname")]
      public string CreatedByExternalPartyName
      {
         get
         {
            return base.GetAttributeValue<string>("createdbyexternalpartyname");
         }
      }
      [DataMember(Name="createdbyexternalpartyyominame")]
      public string CreatedByExternalPartyYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("createdbyexternalpartyyominame");
         }
      }
      [DataMember(Name="createdbyname")]
      public string CreatedByName
      {
         get
         {
            return base.GetAttributeValue<string>("createdbyname");
         }
      }
      [DataMember(Name="createdbyyominame")]
      public string CreatedByYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("createdbyyominame");
         }
      }
      [DataMember(Name="createdon")]
      public System.Nullable<System.DateTime> CreatedOn
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
         }
      }
      [DataMember(Name="createdonbehalfbyname")]
      public string CreatedOnBehalfByName
      {
         get
         {
            return base.GetAttributeValue<string>("createdonbehalfbyname");
         }
      }
      [DataMember(Name="createdonbehalfbyyominame")]
      public string CreatedOnBehalfByYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("createdonbehalfbyyominame");
         }
      }
      [DataMember(Name="creditlimit")]
      public System.Nullable<decimal> CreditLimit
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("creditlimit");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<decimal>>("creditlimit", value);
         }
      }
      [DataMember(Name="creditlimit_base")]
      public System.Nullable<decimal> CreditLimit_Base
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("creditlimit_base");
         }
      }
      [DataMember(Name="creditonhold")]
      public System.Nullable<bool> CreditOnHold
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("creditonhold");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("creditonhold", value);
         }
      }
      [DataMember(Name="defaultpricelevelidname")]
      public string DefaultPriceLevelIdName
      {
         get
         {
            return base.GetAttributeValue<string>("defaultpricelevelidname");
         }
      }
      [DataMember(Name="description")]
      public string Description
      {
         get
         {
            return base.GetAttributeValue<string>("description");
         }
         set
         {
            base.SetAttributeValue<string>("description", value);
         }
      }
      [DataMember(Name="donotbulkemail")]
      public System.Nullable<bool> DoNotBulkEMail
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("donotbulkemail");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("donotbulkemail", value);
         }
      }
      [DataMember(Name="donotbulkpostalmail")]
      public System.Nullable<bool> DoNotBulkPostalMail
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("donotbulkpostalmail");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("donotbulkpostalmail", value);
         }
      }
      [DataMember(Name="donotemail")]
      public System.Nullable<bool> DoNotEMail
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("donotemail");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("donotemail", value);
         }
      }
      [DataMember(Name="donotfax")]
      public System.Nullable<bool> DoNotFax
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("donotfax");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("donotfax", value);
         }
      }
      [DataMember(Name="donotphone")]
      public System.Nullable<bool> DoNotPhone
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("donotphone");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("donotphone", value);
         }
      }
      [DataMember(Name="donotpostalmail")]
      public System.Nullable<bool> DoNotPostalMail
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("donotpostalmail");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("donotpostalmail", value);
         }
      }
      [DataMember(Name="donotsendmm")]
      public System.Nullable<bool> DoNotSendMM
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("donotsendmm");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("donotsendmm", value);
         }
      }
      [DataMember(Name="emailaddress1")]
      public string EMailAddress1
      {
         get
         {
            return base.GetAttributeValue<string>("emailaddress1");
         }
         set
         {
            base.SetAttributeValue<string>("emailaddress1", value);
         }
      }
      [DataMember(Name="emailaddress2")]
      public string EMailAddress2
      {
         get
         {
            return base.GetAttributeValue<string>("emailaddress2");
         }
         set
         {
            base.SetAttributeValue<string>("emailaddress2", value);
         }
      }
      [DataMember(Name="emailaddress3")]
      public string EMailAddress3
      {
         get
         {
            return base.GetAttributeValue<string>("emailaddress3");
         }
         set
         {
            base.SetAttributeValue<string>("emailaddress3", value);
         }
      }
      [DataMember(Name="entityimage_timestamp")]
      public System.Nullable<long> EntityImage_Timestamp
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
         }
      }
      [DataMember(Name="entityimage_url")]
      public string EntityImage_URL
      {
         get
         {
            return base.GetAttributeValue<string>("entityimage_url");
         }
      }
      [DataMember(Name="entityimageid")]
      public System.Nullable<System.Guid> EntityImageId
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
         }
      }
      [DataMember(Name="exchangerate")]
      public System.Nullable<decimal> ExchangeRate
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
         }
      }
      [DataMember(Name="fax")]
      public string Fax
      {
         get
         {
            return base.GetAttributeValue<string>("fax");
         }
         set
         {
            base.SetAttributeValue<string>("fax", value);
         }
      }
      [DataMember(Name="followemail")]
      public System.Nullable<bool> FollowEmail
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("followemail");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("followemail", value);
         }
      }
      [DataMember(Name="ftpsiteurl")]
      public string FtpSiteURL
      {
         get
         {
            return base.GetAttributeValue<string>("ftpsiteurl");
         }
         set
         {
            base.SetAttributeValue<string>("ftpsiteurl", value);
         }
      }
      [DataMember(Name="ic_businesskey")]
      public string ic_BusinessKey
      {
         get
         {
            return base.GetAttributeValue<string>("ic_businesskey");
         }
         set
         {
            base.SetAttributeValue<string>("ic_businesskey", value);
         }
      }
      [DataMember(Name="ic_city")]
      public string ic_City
      {
         get
         {
            return base.GetAttributeValue<string>("ic_city");
         }
         set
         {
            base.SetAttributeValue<string>("ic_city", value);
         }
      }
      [DataMember(Name="ic_cityidname")]
      public string ic_CityIDName
      {
         get
         {
            return base.GetAttributeValue<string>("ic_cityidname");
         }
      }
      [DataMember(Name="ic_countryidname")]
      public string ic_CountryIDName
      {
         get
         {
            return base.GetAttributeValue<string>("ic_countryidname");
         }
      }
      [DataMember(Name="ic_externalid")]
      public string ic_ExternalID
      {
         get
         {
            return base.GetAttributeValue<string>("ic_externalid");
         }
         set
         {
            base.SetAttributeValue<string>("ic_externalid", value);
         }
      }
      [DataMember(Name="ic_franchiseeidname")]
      public string ic_FranchiseeIDName
      {
         get
         {
            return base.GetAttributeValue<string>("ic_franchiseeidname");
         }
      }
      [DataMember(Name="ic_gstumber")]
      public string ic_gstumber
      {
         get
         {
            return base.GetAttributeValue<string>("ic_gstumber");
         }
         set
         {
            base.SetAttributeValue<string>("ic_gstumber", value);
         }
      }
      [DataMember(Name="ic_mailingname")]
      public string ic_MailingName
      {
         get
         {
            return base.GetAttributeValue<string>("ic_mailingname");
         }
         set
         {
            base.SetAttributeValue<string>("ic_mailingname", value);
         }
      }
      [DataMember(Name="ic_pstnumber")]
      public string ic_pstnumber
      {
         get
         {
            return base.GetAttributeValue<string>("ic_pstnumber");
         }
         set
         {
            base.SetAttributeValue<string>("ic_pstnumber", value);
         }
      }
      [DataMember(Name="ic_stateprovinceidname")]
      public string ic_StateProvinceIDName
      {
         get
         {
            return base.GetAttributeValue<string>("ic_stateprovinceidname");
         }
      }
      [DataMember(Name="ic_street1")]
      public string ic_Street1
      {
         get
         {
            return base.GetAttributeValue<string>("ic_street1");
         }
         set
         {
            base.SetAttributeValue<string>("ic_street1", value);
         }
      }
      [DataMember(Name="ic_street2")]
      public string ic_Street2
      {
         get
         {
            return base.GetAttributeValue<string>("ic_street2");
         }
         set
         {
            base.SetAttributeValue<string>("ic_street2", value);
         }
      }
      [DataMember(Name="ic_street3")]
      public string ic_Street3
      {
         get
         {
            return base.GetAttributeValue<string>("ic_street3");
         }
         set
         {
            base.SetAttributeValue<string>("ic_street3", value);
         }
      }
      [DataMember(Name="ic_street4")]
      public string ic_Street4
      {
         get
         {
            return base.GetAttributeValue<string>("ic_street4");
         }
         set
         {
            base.SetAttributeValue<string>("ic_street4", value);
         }
      }
      [DataMember(Name="ic_synchronizationremarks")]
      public string ic_SynchronizationRemarks
      {
         get
         {
            return base.GetAttributeValue<string>("ic_synchronizationremarks");
         }
         set
         {
            base.SetAttributeValue<string>("ic_synchronizationremarks", value);
         }
      }
      [DataMember(Name="ic_tenanthealthreviewcomments")]
      public string ic_TenantHealthReviewComments
      {
         get
         {
            return base.GetAttributeValue<string>("ic_tenanthealthreviewcomments");
         }
         set
         {
            base.SetAttributeValue<string>("ic_tenanthealthreviewcomments", value);
         }
      }
      [DataMember(Name="ic_tenanthealthreviewcomplete")]
      public System.Nullable<bool> ic_TenantHealthReviewComplete
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("ic_tenanthealthreviewcomplete");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("ic_tenanthealthreviewcomplete", value);
         }
      }
      [DataMember(Name="ic_tenanthealthreviewdate")]
      public System.Nullable<System.DateTime> ic_TenantHealthReviewDate
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("ic_tenanthealthreviewdate");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<System.DateTime>>("ic_tenanthealthreviewdate", value);
         }
      }
      [DataMember(Name="ic_zippostalcode")]
      public string ic_ZIPPostalCode
      {
         get
         {
            return base.GetAttributeValue<string>("ic_zippostalcode");
         }
         set
         {
            base.SetAttributeValue<string>("ic_zippostalcode", value);
         }
      }
      [DataMember(Name="importsequencenumber")]
      public System.Nullable<int> ImportSequenceNumber
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
         }
      }
      [DataMember(Name="lastonholdtime")]
      public System.Nullable<System.DateTime> LastOnHoldTime
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime", value);
         }
      }
      [DataMember(Name="lastusedincampaign")]
      public System.Nullable<System.DateTime> LastUsedInCampaign
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("lastusedincampaign");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<System.DateTime>>("lastusedincampaign", value);
         }
      }
      [DataMember(Name="marketcap")]
      public System.Nullable<decimal> MarketCap
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("marketcap");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<decimal>>("marketcap", value);
         }
      }
      [DataMember(Name="marketcap_base")]
      public System.Nullable<decimal> MarketCap_Base
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("marketcap_base");
         }
      }
      [DataMember(Name="marketingonly")]
      public System.Nullable<bool> MarketingOnly
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("marketingonly");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("marketingonly", value);
         }
      }
      [DataMember(Name="masteraccountidname")]
      public string MasterAccountIdName
      {
         get
         {
            return base.GetAttributeValue<string>("masteraccountidname");
         }
      }
      [DataMember(Name="masteraccountidyominame")]
      public string MasterAccountIdYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("masteraccountidyominame");
         }
      }
      [DataMember(Name="merged")]
      public System.Nullable<bool> Merged
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("merged");
         }
      }
      [DataMember(Name="modifiedbyexternalpartyname")]
      public string ModifiedByExternalPartyName
      {
         get
         {
            return base.GetAttributeValue<string>("modifiedbyexternalpartyname");
         }
      }
      [DataMember(Name="modifiedbyexternalpartyyominame")]
      public string ModifiedByExternalPartyYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("modifiedbyexternalpartyyominame");
         }
      }
      [DataMember(Name="modifiedbyname")]
      public string ModifiedByName
      {
         get
         {
            return base.GetAttributeValue<string>("modifiedbyname");
         }
      }
      [DataMember(Name="modifiedbyyominame")]
      public string ModifiedByYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("modifiedbyyominame");
         }
      }
      [DataMember(Name="modifiedon")]
      public System.Nullable<System.DateTime> ModifiedOn
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
         }
      }
      [DataMember(Name="modifiedonbehalfbyname")]
      public string ModifiedOnBehalfByName
      {
         get
         {
            return base.GetAttributeValue<string>("modifiedonbehalfbyname");
         }
      }
      [DataMember(Name="modifiedonbehalfbyyominame")]
      public string ModifiedOnBehalfByYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("modifiedonbehalfbyyominame");
         }
      }
      [DataMember(Name="name")]
      public string Name
      {
         get
         {
            return base.GetAttributeValue<string>("name");
         }
         set
         {
            base.SetAttributeValue<string>("name", value);
         }
      }
      [DataMember(Name="numberofemployees")]
      public System.Nullable<int> NumberOfEmployees
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("numberofemployees");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<int>>("numberofemployees", value);
         }
      }
      [DataMember(Name="onholdtime")]
      public System.Nullable<int> OnHoldTime
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("onholdtime");
         }
      }
      [DataMember(Name="opendeals")]
      public System.Nullable<int> OpenDeals
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("opendeals");
         }
      }
      [DataMember(Name="opendeals_date")]
      public System.Nullable<System.DateTime> OpenDeals_Date
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("opendeals_date");
         }
      }
      [DataMember(Name="opendeals_state")]
      public System.Nullable<int> OpenDeals_State
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("opendeals_state");
         }
      }
      [DataMember(Name="openrevenue")]
      public System.Nullable<decimal> OpenRevenue
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("openrevenue");
         }
      }
      [DataMember(Name="openrevenue_base")]
      public System.Nullable<decimal> OpenRevenue_Base
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("openrevenue_base");
         }
      }
      [DataMember(Name="openrevenue_date")]
      public System.Nullable<System.DateTime> OpenRevenue_Date
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("openrevenue_date");
         }
      }
      [DataMember(Name="openrevenue_state")]
      public System.Nullable<int> OpenRevenue_State
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("openrevenue_state");
         }
      }
      [DataMember(Name="originatingleadidname")]
      public string OriginatingLeadIdName
      {
         get
         {
            return base.GetAttributeValue<string>("originatingleadidname");
         }
      }
      [DataMember(Name="originatingleadidyominame")]
      public string OriginatingLeadIdYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("originatingleadidyominame");
         }
      }
      [DataMember(Name="overriddencreatedon")]
      public System.Nullable<System.DateTime> OverriddenCreatedOn
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
         }
      }
      [DataMember(Name="owneridname")]
      public string OwnerIdName
      {
         get
         {
            return base.GetAttributeValue<string>("owneridname");
         }
      }
      [DataMember(Name="owneridtype")]
      public string OwnerIdType
      {
         get
         {
            return base.GetAttributeValue<string>("owneridtype");
         }
         set
         {
            base.SetAttributeValue<string>("owneridtype", value);
         }
      }
      [DataMember(Name="owneridyominame")]
      public string OwnerIdYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("owneridyominame");
         }
      }
      [DataMember(Name="parentaccountidname")]
      public string ParentAccountIdName
      {
         get
         {
            return base.GetAttributeValue<string>("parentaccountidname");
         }
      }
      [DataMember(Name="parentaccountidyominame")]
      public string ParentAccountIdYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("parentaccountidyominame");
         }
      }
      [DataMember(Name="participatesinworkflow")]
      public System.Nullable<bool> ParticipatesInWorkflow
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<bool>>("participatesinworkflow");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<bool>>("participatesinworkflow", value);
         }
      }
      [DataMember(Name="preferredequipmentidname")]
      public string PreferredEquipmentIdName
      {
         get
         {
            return base.GetAttributeValue<string>("preferredequipmentidname");
         }
      }
      [DataMember(Name="preferredserviceidname")]
      public string PreferredServiceIdName
      {
         get
         {
            return base.GetAttributeValue<string>("preferredserviceidname");
         }
      }
      [DataMember(Name="preferredsystemuseridname")]
      public string PreferredSystemUserIdName
      {
         get
         {
            return base.GetAttributeValue<string>("preferredsystemuseridname");
         }
      }
      [DataMember(Name="preferredsystemuseridyominame")]
      public string PreferredSystemUserIdYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("preferredsystemuseridyominame");
         }
      }
      [DataMember(Name="primarycontactidname")]
      public string PrimaryContactIdName
      {
         get
         {
            return base.GetAttributeValue<string>("primarycontactidname");
         }
      }
      [DataMember(Name="primarycontactidyominame")]
      public string PrimaryContactIdYomiName
      {
         get
         {
            return base.GetAttributeValue<string>("primarycontactidyominame");
         }
      }
      [DataMember(Name="primarysatoriid")]
      public string PrimarySatoriId
      {
         get
         {
            return base.GetAttributeValue<string>("primarysatoriid");
         }
         set
         {
            base.SetAttributeValue<string>("primarysatoriid", value);
         }
      }
      [DataMember(Name="primarytwitterid")]
      public string PrimaryTwitterId
      {
         get
         {
            return base.GetAttributeValue<string>("primarytwitterid");
         }
         set
         {
            base.SetAttributeValue<string>("primarytwitterid", value);
         }
      }
      [DataMember(Name="processid")]
      public System.Nullable<System.Guid> ProcessId
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.Guid>>("processid");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<System.Guid>>("processid", value);
         }
      }
      [DataMember(Name="revenue")]
      public System.Nullable<decimal> Revenue
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("revenue");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<decimal>>("revenue", value);
         }
      }
      [DataMember(Name="revenue_base")]
      public System.Nullable<decimal> Revenue_Base
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<decimal>>("revenue_base");
         }
      }
      [DataMember(Name="sharesoutstanding")]
      public System.Nullable<int> SharesOutstanding
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("sharesoutstanding");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<int>>("sharesoutstanding", value);
         }
      }
      [DataMember(Name="sic")]
      public string SIC
      {
         get
         {
            return base.GetAttributeValue<string>("sic");
         }
         set
         {
            base.SetAttributeValue<string>("sic", value);
         }
      }
      [DataMember(Name="slainvokedidname")]
      public string SLAInvokedIdName
      {
         get
         {
            return base.GetAttributeValue<string>("slainvokedidname");
         }
      }
      [DataMember(Name="slaname")]
      public string SLAName
      {
         get
         {
            return base.GetAttributeValue<string>("slaname");
         }
      }
      [DataMember(Name="stageid")]
      public System.Nullable<System.Guid> StageId
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<System.Guid>>("stageid", value);
         }
      }
      [DataMember(Name="stockexchange")]
      public string StockExchange
      {
         get
         {
            return base.GetAttributeValue<string>("stockexchange");
         }
         set
         {
            base.SetAttributeValue<string>("stockexchange", value);
         }
      }
      [DataMember(Name="teamsfollowed")]
      public System.Nullable<int> TeamsFollowed
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("teamsfollowed");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<int>>("teamsfollowed", value);
         }
      }
      [DataMember(Name="telephone1")]
      public string Telephone1
      {
         get
         {
            return base.GetAttributeValue<string>("telephone1");
         }
         set
         {
            base.SetAttributeValue<string>("telephone1", value);
         }
      }
      [DataMember(Name="telephone2")]
      public string Telephone2
      {
         get
         {
            return base.GetAttributeValue<string>("telephone2");
         }
         set
         {
            base.SetAttributeValue<string>("telephone2", value);
         }
      }
      [DataMember(Name="telephone3")]
      public string Telephone3
      {
         get
         {
            return base.GetAttributeValue<string>("telephone3");
         }
         set
         {
            base.SetAttributeValue<string>("telephone3", value);
         }
      }
      [DataMember(Name="territoryidname")]
      public string TerritoryIdName
      {
         get
         {
            return base.GetAttributeValue<string>("territoryidname");
         }
      }
      [DataMember(Name="tickersymbol")]
      public string TickerSymbol
      {
         get
         {
            return base.GetAttributeValue<string>("tickersymbol");
         }
         set
         {
            base.SetAttributeValue<string>("tickersymbol", value);
         }
      }
      [DataMember(Name="timespentbymeonemailandmeetings")]
      public string TimeSpentByMeOnEmailAndMeetings
      {
         get
         {
            return base.GetAttributeValue<string>("timespentbymeonemailandmeetings");
         }
      }
      [DataMember(Name="timezoneruleversionnumber")]
      public System.Nullable<int> TimeZoneRuleVersionNumber
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber", value);
         }
      }
      [DataMember(Name="transactioncurrencyidname")]
      public string TransactionCurrencyIdName
      {
         get
         {
            return base.GetAttributeValue<string>("transactioncurrencyidname");
         }
      }
      [DataMember(Name="traversedpath")]
      public string TraversedPath
      {
         get
         {
            return base.GetAttributeValue<string>("traversedpath");
         }
         set
         {
            base.SetAttributeValue<string>("traversedpath", value);
         }
      }
      [DataMember(Name="utcconversiontimezonecode")]
      public System.Nullable<int> UTCConversionTimeZoneCode
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
         }
         set
         {
            base.SetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode", value);
         }
      }
      [DataMember(Name="versionnumber")]
      public System.Nullable<long> VersionNumber
      {
         get
         {
            return base.GetAttributeValue<System.Nullable<long>>("versionnumber");
         }
      }
      [DataMember(Name="websiteurl")]
      public string WebSiteURL
      {
         get
         {
            return base.GetAttributeValue<string>("websiteurl");
         }
         set
         {
            base.SetAttributeValue<string>("websiteurl", value);
         }
      }
      [DataMember(Name="yominame")]
      public string YomiName
      {
         get
         {
            return base.GetAttributeValue<string>("yominame");
         }
         set
         {
            base.SetAttributeValue<string>("yominame", value);
         }
      }
   }
}
