//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.entities
{
   using System;
   using System.Collections.Generic;
   
   public partial class Contact
   {
      public System.Guid ContactId { get;  }
      public string EMailAddress3 { get; set;  }
      public string EMailAddress2 { get; set;  }
      public string EMailAddress1 { get; set;  }
      public string Address1_City { get; set;  }
      public string Address3_Line1 { get; set;  }
      public string Address1_Line1 { get; set;  }
      public string ManagerPhone { get; set;  }
      public System.Nullable<System.DateTime> ModifiedOn { get;  }
      public System.Nullable<decimal> Aging90 { get;  }
      public string WebSiteUrl { get; set;  }
      public System.Nullable<bool> msdyn_gdproptout { get; set;  }
      public System.Nullable<double> Address1_Longitude { get; set;  }
      public System.Nullable<bool> DoNotPostalMail { get; set;  }
      public string YomiFullName { get;  }
      public string Company { get; set;  }
      public System.Nullable<long> EntityImage_Timestamp { get;  }
      public System.Nullable<decimal> Aging30 { get;  }
      public string ic_CompanyIDName { get;  }
      public string Address3_Telephone1 { get; set;  }
      public string Address3_Line3 { get; set;  }
      public string Address2_County { get; set;  }
      public System.Nullable<bool> CreditOnHold { get; set;  }
      public string TransactionCurrencyIdName { get;  }
      public System.Nullable<bool> DoNotBulkPostalMail { get; set;  }
      public string EntityImage_URL { get;  }
      public string Address3_Telephone3 { get; set;  }
      public string PreferredSystemUserIdYomiName { get;  }
      public string SLAInvokedId { get;  }
      public string CreatedByExternalPartyName { get;  }
      public string Address3_PrimaryContactName { get; set;  }
      public string ModifiedByExternalPartyYomiName { get;  }
      public string OriginatingLeadId { get;  }
      public string PreferredSystemUserIdName { get;  }
      public string OwningBusinessUnit { get;  }
      public string Address2_StateOrProvince { get; set;  }
      public string CreatedByExternalPartyYomiName { get;  }
      public string TimeSpentByMeOnEmailAndMeetings { get;  }
      public string MobilePhone { get; set;  }
      public string ParentCustomerIdYomiName { get;  }
      public string Address2_Country { get; set;  }
      public System.Nullable<int> TeamsFollowed { get; set;  }
      public string Address2_Line2 { get; set;  }
      public string AccountId { get;  }
      public string SLAId { get; set;  }
      public string PreferredServiceId { get; set;  }
      public string AssistantPhone { get; set;  }
      public string OwnerIdYomiName { get;  }
      public string ParentContactId { get;  }
      public System.Nullable<double> Address3_Longitude { get; set;  }
      public System.Nullable<int> OnHoldTime { get;  }
      public string ParentContactIdYomiName { get;  }
      public string Address3_Fax { get; set;  }
      public System.Nullable<decimal> CreditLimit { get; set;  }
      public System.Nullable<System.DateTime> BirthDate { get; set;  }
      public string OriginatingLeadIdName { get;  }
      public System.Nullable<int> Address1_UTCOffset { get; set;  }
      public System.Nullable<long> VersionNumber { get;  }
      public string Address1_Telephone1 { get; set;  }
      public string Address3_UPSZone { get; set;  }
      public System.Nullable<decimal> ExchangeRate { get;  }
      public string Address3_Composite { get;  }
      public string Address2_Line1 { get; set;  }
      public string ModifiedByExternalPartyName { get;  }
      public string Telephone3 { get; set;  }
      public string Address2_City { get; set;  }
      public string Address3_Line2 { get; set;  }
      public System.Nullable<bool> MarketingOnly { get; set;  }
      public System.Nullable<double> Address2_Latitude { get; set;  }
      public System.Nullable<System.DateTime> CreatedOn { get;  }
      public System.Nullable<bool> DoNotBulkEMail { get; set;  }
      public string SLAName { get;  }
      public string CreatedByYomiName { get;  }
      public System.Nullable<bool> DoNotFax { get; set;  }
      public System.Nullable<decimal> Aging90_Base { get;  }
      public string Address1_Composite { get;  }
      public string FirstName { get; set;  }
      public System.Nullable<bool> DoNotSendMM { get; set;  }
      public string Callback { get; set;  }
      public string ic_BusinessKey { get; set;  }
      public string Address2_PostalCode { get; set;  }
      public System.Nullable<System.DateTime> LastUsedInCampaign { get; set;  }
      public string EmployeeId { get; set;  }
      public string ModifiedByYomiName { get;  }
      public string GovernmentId { get; set;  }
      public string Address2_Line3 { get; set;  }
      public string Description { get; set;  }
      public string ModifiedBy { get;  }
      public System.Nullable<int> TimeZoneRuleVersionNumber { get; set;  }
      public string Address1_County { get; set;  }
      public string Address2_Telephone2 { get; set;  }
      public string ModifiedOnBehalfBy { get;  }
      public System.Nullable<bool> DoNotEMail { get; set;  }
      public System.Nullable<decimal> Aging60_Base { get;  }
      public string Pager { get; set;  }
      public string Address2_PostOfficeBox { get; set;  }
      public string Address2_Telephone1 { get; set;  }
      public string YomiLastName { get; set;  }
      public string Address2_Telephone3 { get; set;  }
      public string OriginatingLeadIdYomiName { get;  }
      public string PreferredEquipmentIdName { get;  }
      public string DefaultPriceLevelId { get; set;  }
      public System.Guid? Address1_AddressId { get; set;  }
      public string TraversedPath { get; set;  }
      public string ic_CompanyID { get; set;  }
      public System.Nullable<decimal> CreditLimit_Base { get;  }
      public System.Nullable<decimal> AnnualIncome { get; set;  }
      public string OwningUser { get;  }
      public string Address2_Composite { get;  }
      public string Address2_Name { get; set;  }
      public string Address1_Country { get; set;  }
      public string MiddleName { get; set;  }
      public string Address3_Telephone2 { get; set;  }
      public System.Guid EntityImageId { get;  }
      public System.Nullable<decimal> Aging60 { get;  }
      public string ParentCustomerIdName { get;  }
      public string OwnerIdName { get;  }
      public System.Nullable<System.DateTime> OverriddenCreatedOn { get;  }
      public string CreatedByExternalParty { get;  }
      public string Suffix { get; set;  }
      public string SLAInvokedIdName { get;  }
      public System.Nullable<bool> ParticipatesInWorkflow { get; set;  }
      public string OwningTeam { get;  }
      public string Address1_StateOrProvince { get; set;  }
      public string ExternalUserIdentifier { get; set;  }
      public string PreferredServiceIdName { get;  }
      public System.Nullable<int> Address3_UTCOffset { get; set;  }
      public string ModifiedOnBehalfByName { get;  }
      public string CreatedOnBehalfByName { get;  }
      public string Address1_Line3 { get; set;  }
      public System.Guid? ProcessId { get; set;  }
      public string CreatedOnBehalfBy { get;  }
      public string MasterContactIdName { get;  }
      public string JobTitle { get; set;  }
      public string NickName { get; set;  }
      public string TransactionCurrencyId { get; set;  }
      public string ManagerName { get; set;  }
      public string Address1_Telephone2 { get; set;  }
      public string Address1_Telephone3 { get; set;  }
      public System.Nullable<double> Address3_Latitude { get; set;  }
      public System.Nullable<bool> IsBackofficeCustomer { get; set;  }
      public string CreatedOnBehalfByYomiName { get;  }
      public string ChildrensNames { get; set;  }
      public string Fax { get; set;  }
      public string MasterId { get;  }
      public string MasterContactIdYomiName { get;  }
      public string AssistantName { get; set;  }
      public string YomiMiddleName { get; set;  }
      public string OwnerId { get; set;  }
      public string Address3_Country { get; set;  }
      public System.Nullable<int> Address2_UTCOffset { get; set;  }
      public System.Guid? StageId { get; set;  }
      public string Address2_Fax { get; set;  }
      public System.Nullable<bool> Merged { get;  }
      public string OwnerIdType { get; set;  }
      public string Address3_County { get; set;  }
      public System.Nullable<double> Address2_Longitude { get; set;  }
      public string ModifiedByExternalParty { get;  }
      public string FtpSiteUrl { get; set;  }
      public string PreferredEquipmentId { get; set;  }
      public string CreatedByName { get;  }
      public System.Nullable<bool> DoNotPhone { get; set;  }
      public string AccountIdName { get;  }
      public string Address1_PrimaryContactName { get; set;  }
      public System.Nullable<System.DateTime> LastOnHoldTime { get; set;  }
      public string Address1_Line2 { get; set;  }
      public string YomiFirstName { get; set;  }
      public string CreatedBy { get;  }
      public string ParentCustomerId { get; set;  }
      public System.Nullable<decimal> AnnualIncome_Base { get;  }
      public System.Nullable<bool> FollowEmail { get; set;  }
      public string SpousesName { get; set;  }
      public string Address3_Name { get; set;  }
      public string Salutation { get; set;  }
      public string Address1_PostalCode { get; set;  }
      public string Address2_UPSZone { get; set;  }
      public string Address3_PostalCode { get; set;  }
      public string DefaultPriceLevelIdName { get;  }
      public System.Guid? Address2_AddressId { get; set;  }
      public string Home2 { get; set;  }
      public string Address3_StateOrProvince { get; set;  }
      public System.Nullable<System.DateTime> Anniversary { get; set;  }
      public System.Nullable<int> ImportSequenceNumber { get;  }
      public string Telephone2 { get; set;  }
      public string Department { get; set;  }
      public string PreferredSystemUserId { get; set;  }
      public string Address3_City { get; set;  }
      public string Business2 { get; set;  }
      public string Telephone1 { get; set;  }
      public System.Nullable<decimal> Aging30_Base { get;  }
      public string Address1_Name { get; set;  }
      public string Address1_Fax { get; set;  }
      public System.Nullable<double> Address1_Latitude { get; set;  }
      public string Address3_PostOfficeBox { get; set;  }
      public string ParentCustomerIdType { get; set;  }
      public string ParentContactIdName { get;  }
      public string ModifiedByName { get;  }
      public string ic_CompanyIDYomiName { get;  }
      public string Address1_UPSZone { get; set;  }
      public string LastName { get; set;  }
      public string AccountIdYomiName { get;  }
      public string ModifiedOnBehalfByYomiName { get;  }
      public System.Nullable<int> UTCConversionTimeZoneCode { get; set;  }
      public System.Nullable<int> NumberOfChildren { get; set;  }
      public string Address1_PostOfficeBox { get; set;  }
      public string Address2_PrimaryContactName { get; set;  }
      public string FullName { get;  }
      public System.Guid? Address3_AddressId { get; set;  }
   }
}
