//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.entities
{
   using System;
   using System.Collections.Generic;
   
   public partial class ic_deal
   {
      public System.Nullable<long> VersionNumber { get;  }
      public System.Nullable<System.DateTime> CreatedOn { get;  }
      public string ic_TradeNameID { get; set;  }
      public string ic_TenantCoordinationContactID { get; set;  }
      public string ic_BrokerID { get; set;  }
      public string ic_DealStage { get; set;  }
      public string ModifiedByYomiName { get;  }
      public string ic_GuarantorID { get; set;  }
      public string OwnerIdType { get; set;  }
      public string CreatedOnBehalfBy { get;  }
      public string ic_name { get; set;  }
      public string ModifiedByName { get;  }
      public string OwnerIdName { get;  }
      public string ic_BrokerIDName { get;  }
      public System.Nullable<System.DateTime> OverriddenCreatedOn { get;  }
      public System.Nullable<int> ic_DesiredArea { get; set;  }
      public System.Guid ic_dealId { get;  }
      public string ic_NegociatorIDYomiName { get;  }
      public string ic_AssetIDName { get;  }
      public string CreatedOnBehalfByYomiName { get;  }
      public string ModifiedOnBehalfBy { get;  }
      public string ic_PrimaryConceptID { get; set;  }
      public string ic_CommentsProposal { get; set;  }
      public string ic_TenantIDYomiName { get;  }
      public string OwningTeam { get;  }
      public string ic_NegociatorID { get; set;  }
      public string ic_GuarantorIDYomiName { get;  }
      public string ic_TenantCoordinationContactIDYomiName { get;  }
      public System.Nullable<int> TimeZoneRuleVersionNumber { get; set;  }
      public string ic_SelectedScenarioID { get; set;  }
      public string ic_PrimaryConceptIDName { get;  }
      public System.Nullable<int> ic_PrimaryConceptGLA { get; set;  }
      public string ic_LeasingContactIDYomiName { get;  }
      public string EmailAddress { get; set;  }
      public string ic_LeasingContact2IDYomiName { get;  }
      public string ic_LegalContactID { get; set;  }
      public string traversedpath { get; set;  }
      public string CreatedOnBehalfByName { get;  }
      public string ic_LeasingContact2IDName { get;  }
      public string ic_OriginalDealID { get; set;  }
      public string CreatedBy { get;  }
      public System.Nullable<int> UTCConversionTimeZoneCode { get; set;  }
      public string ic_LegalContactIDName { get;  }
      public string ic_GuarantorIDName { get;  }
      public string ic_NegociatorIDName { get;  }
      public System.Nullable<bool> ic_IsUseClauseChecked { get; set;  }
      public string OwnerId { get; set;  }
      public System.Nullable<System.DateTime> ModifiedOn { get;  }
      public System.Nullable<int> ImportSequenceNumber { get;  }
      public string OwnerIdYomiName { get;  }
      public string ic_LegalContactIDYomiName { get;  }
      public string ic_TenantCoordinationContactIDName { get;  }
      public string ic_SelectedScenarioIDName { get;  }
      public System.Guid? processid { get; set;  }
      public string ic_DealCategoryID { get; set;  }
      public string ic_DealSubCategoryIDName { get;  }
      public string ic_DocumentTypeID { get; set;  }
      public string CreatedByName { get;  }
      public string ic_BrokerIDIdType { get; set;  }
      public string ModifiedOnBehalfByName { get;  }
      public string ic_OriginalDealIDName { get;  }
      public System.Guid? stageid { get; set;  }
      public string ic_IssueClauseComments { get; set;  }
      public string ic_BusinessKey { get; set;  }
      public string ic_LeasingContactID { get; set;  }
      public string ic_PrimaryConceptAtCreation { get; set;  }
      public string ic_CommentsContact { get; set;  }
      public string ic_DocumentTypeIDName { get;  }
      public string ModifiedBy { get;  }
      public string ic_TenantIDName { get;  }
      public string CreatedByYomiName { get;  }
      public string OwningUser { get;  }
      public string ic_PrimaryConceptAtCreationName { get;  }
      public string OwningBusinessUnit { get;  }
      public string ic_AssetID { get; set;  }
      public System.Nullable<int> ic_TenantReviewPeriod { get; set;  }
      public string ic_DealSynopsis { get; set;  }
      public string ic_DealCategoryIDName { get;  }
      public string ic_TenantID { get; set;  }
      public string ic_TradeNameIDName { get;  }
      public string ModifiedOnBehalfByYomiName { get;  }
      public string ic_LeasingContact2ID { get; set;  }
      public string ic_FileNumber { get; set;  }
      public string ic_BrokerIDYomiName { get;  }
      public string ic_DealSubCategoryID { get; set;  }
      public string ic_BuildingIDName { get;  }
      public string ic_LeasingContactIDName { get;  }
      public string ic_BuildingID { get; set;  }
      public System.Nullable<bool> ic_IsGrossDeal { get; set;  }
   }
}
